---
- name: test for playbook 1
  hosts: testVM
  tasks:
  - name: sudo access
    lineinfile: 
      path: /etc/sudoers
      regexp: '^dummy_new'
      line: 'dummy_new ALL=(ALL) NOPASSWD: ALL'
...
